const menuButton=document.querySelector('.menu-button'),siteNav=document.querySelector('nav'),toast=document.getElementById('toast');
function showToast(message){toast.textContent=message;toast.classList.add('show');clearTimeout(showToast.timer);showToast.timer=setTimeout(()=>toast.classList.remove('show'),2200)}
menuButton.addEventListener('click',()=>{const open=siteNav.classList.toggle('open');menuButton.setAttribute('aria-expanded',String(open))});
siteNav.querySelectorAll('a').forEach(link=>link.addEventListener('click',()=>{siteNav.classList.remove('open');menuButton.setAttribute('aria-expanded','false')}));
document.querySelectorAll('[data-copy]').forEach(button=>button.addEventListener('click',async()=>{const address=document.getElementById(button.dataset.copy).textContent.trim();try{await navigator.clipboard.writeText(address)}catch{const area=document.createElement('textarea');area.value=address;area.style.position='fixed';area.style.opacity='0';document.body.appendChild(area);area.select();document.execCommand('copy');area.remove()}const original=button.textContent;button.textContent='Copied ✓';showToast('Wallet address copied');setTimeout(()=>button.textContent=original,1800)}));

function highlightPaymentNetwork(network){document.querySelectorAll('[data-network-card]').forEach(card=>card.classList.toggle('active',card.dataset.networkCard===network))}
function isValidTelegram(value){return /^@[A-Za-z0-9_]{5,32}$/.test(value)}
function isValidTransactionId(network,value){const ownAddresses=new Set(['0x644ed89caecc120d3a3180e9f20a90d970cfa3e8'.toLowerCase(),'TJCFS6hDKsEnquGuvw43krk141QLvHnGbG'.toLowerCase()]);if(ownAddresses.has(value.toLowerCase()))return false;if(network==='BEP20'||network==='ERC20')return /^0x[a-fA-F0-9]{64}$/.test(value);return /^[a-fA-F0-9]{64}$/.test(value)}
const networkSelect=document.getElementById('network');
networkSelect.addEventListener('change',()=>highlightPaymentNetwork(networkSelect.value));
highlightPaymentNetwork(networkSelect.value);

const form=document.getElementById('payment-form');
function setError(id,message){const input=document.getElementById(id);input.classList.toggle('invalid',Boolean(message));document.querySelector(`[data-error="${id}"]`).textContent=message}
form.addEventListener('submit',event=>{event.preventDefault();const telegram=document.getElementById('telegram').value.trim(),amount=Number(document.getElementById('amount').value),product=document.getElementById('product').value,network=document.getElementById('network').value,txid=document.getElementById('txid').value.trim();const telegramOk=isValidTelegram(telegram),txidOk=isValidTransactionId(network,txid);setError('telegram',telegramOk?'':'Enter a valid username starting with @.');setError('amount',amount>=10?'':'Minimum deposit is 10 USDT.');setError('txid',txidOk?'':'Enter the completed payment TxID—not a wallet address.');if(!telegramOk||amount<10||!txidOk){showToast('Please correct the payment details');return}const message=['EVA AI MARKET — Payment Verification','',`Telegram username: ${telegram}`,`Product: ${product}`,`Amount: ${amount.toFixed(2)} USDT`,`Network: ${network}`,`Transaction ID: ${txid}`].join('\n');window.open(`https://t.me/eva007_8?text=${encodeURIComponent(message)}`,'_blank','noopener,noreferrer')});

function sortStoreProducts(products){return [...products].sort((a,b)=>{const aAws=a.category==='AWS Cloud Accounts',bAws=b.category==='AWS Cloud Accounts';if(aAws!==bAws)return aAws?-1:1;if(!aAws)return 0;const size=p=>{const text=`${p.name||''} ${p.subtitle||''}`;const match=text.match(/(\d{1,4})\s*(?:v?cpu|v\b)/i);return match?Number(match[1]):Number((p.name||'').match(/\\d{1,4}/)?.[0]||0)};return size(b)-size(a)})}
const publicStore=document.getElementById('public-store-products');
async function loadPublicStore(){if(!publicStore)return;try{const response=await fetch('/api/store');const body=await response.json();if(!response.ok)throw new Error(body.error||'Store unavailable');publicStore.innerHTML=sortStoreProducts(body.products).map(product=>`<article class="account-product panel">${publicProductLogo(product)}<span class="product-tag">${escapeStore(product.category)}</span><h3>${escapeStore(product.name)}</h3><p>${escapeStore(product.subtitle)}</p>${publicAwsFeatures(product)}<strong>$${Number(product.price_usd).toFixed(2)} <small>USDT</small></strong><div class="stock-line"><span class="${product.stock>0?'in-stock':'out-stock'}">${product.stock>0?product.stock+' in stock':'Out of stock'}</span><span>${product.warranty_days}-day warranty</span></div><a class="button ${product.stock>0?'secondary':'disabled'}" href="/login.html">${product.stock>0?'Buy with EVA Balance':'Unavailable'}</a></article>`).join('')}catch(error){publicStore.innerHTML=`<article class="panel store-loading">${escapeStore(error.message)} Contact support for current stock.</article>`}}
function publicProductLogo(product){const aws=product.category==='AWS Cloud Accounts';return `<div class="product-logo ${aws?'aws-logo':'claude-logo'}"><span>${aws?'AWS':'AI'}</span><i></i></div>`}
function publicAwsFeatures(product){return product.category==='AWS Cloud Accounts'?'<ul class="aws-features"><li>Claude 4.6 / 4.7 / 4.8 Working</li><li>10K RPM</li><li>Full TDP</li><li>Invoice Paid · Old Account</li><li>Fable 5 Full Quota</li><li>Low Price · High Quality</li><li><a class="official-support-link" href="https://t.me/eva007_8" target="_blank" rel="noopener noreferrer">Contact Official Support</a></li></ul>':''}
function escapeStore(value){return String(value??'').replace(/[&<>'"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[c]))}
loadPublicStore();
