const menuButton=document.querySelector('.menu-button'),siteNav=document.querySelector('nav'),toast=document.getElementById('toast');
function showToast(message){toast.textContent=message;toast.classList.add('show');clearTimeout(showToast.timer);showToast.timer=setTimeout(()=>toast.classList.remove('show'),2200)}
menuButton.addEventListener('click',()=>{const open=siteNav.classList.toggle('open');menuButton.setAttribute('aria-expanded',String(open))});
siteNav.querySelectorAll('a').forEach(link=>link.addEventListener('click',()=>{siteNav.classList.remove('open');menuButton.setAttribute('aria-expanded','false')}));
document.querySelectorAll('[data-copy]').forEach(button=>button.addEventListener('click',async()=>{const address=document.getElementById(button.dataset.copy).textContent.trim();try{await navigator.clipboard.writeText(address)}catch{const area=document.createElement('textarea');area.value=address;area.style.position='fixed';area.style.opacity='0';document.body.appendChild(area);area.select();document.execCommand('copy');area.remove()}const original=button.textContent;button.textContent='Copied ✓';showToast('Wallet address copied');setTimeout(()=>button.textContent=original,1800)}));

const bedrockProvider=[...document.querySelectorAll('.provider')].find(provider=>provider.querySelector('strong')?.textContent.trim()==='AWS Bedrock — Claude');
if(bedrockProvider){const status=bedrockProvider.querySelector('small'),indicator=bedrockProvider.querySelector(':scope > span');if(status)status.textContent='Status: Live & Available';if(indicator)indicator.textContent='✓'}

const heroButtons=document.querySelector('.hero .buttons');
if(heroButtons){const fundButton=[...heroButtons.querySelectorAll('a')].find(link=>/Add Balance|Fund/i.test(link.textContent));if(fundButton){fundButton.classList.remove('secondary');fundButton.classList.add('primary');fundButton.textContent='Login & Submit Deposit';fundButton.href='/login.html'}const notice=document.createElement('p');notice.className='mini-note';notice.style.marginTop='14px';notice.style.padding='12px 14px';notice.style.border='1px solid rgba(65,215,232,.35)';notice.style.borderRadius='12px';notice.style.background='rgba(65,215,232,.08)';notice.innerHTML='<strong>Already paid?</strong> Log in to My Account and submit the successful payment TXID. Your balance is added only after this deposit request is approved.';heroButtons.insertAdjacentElement('afterend',notice)}
const depositNav=[...siteNav.querySelectorAll('a')].find(link=>link.textContent.trim()==='Deposit Credits');if(depositNav){depositNav.href='/login.html';depositNav.textContent='Submit Deposit'}

function highlightPaymentNetwork(network){document.querySelectorAll('[data-network-card]').forEach(card=>card.classList.toggle('active',card.dataset.networkCard===network))}
function isValidTelegram(value){return /^@[A-Za-z0-9_]{5,32}$/.test(value)}
function isValidTransactionId(network,value){const ownAddresses=new Set(['0x644ed89caecc120d3a3180e9f20a90d970cfa3e8'.toLowerCase(),'TJCFS6hDKsEnquGuvw43krk141QLvHnGbG'.toLowerCase()]);if(ownAddresses.has(value.toLowerCase()))return false;if(network==='BEP20'||network==='ERC20')return /^0x[a-fA-F0-9]{64}$/.test(value);return /^[a-fA-F0-9]{64}$/.test(value)}
const networkSelect=document.getElementById('network');
networkSelect.addEventListener('change',()=>highlightPaymentNetwork(networkSelect.value));
highlightPaymentNetwork(networkSelect.value);

const form=document.getElementById('payment-form');
function setError(id,message){const input=document.getElementById(id);input.classList.toggle('invalid',Boolean(message));document.querySelector(`[data-error="${id}"]`).textContent=message}
form.addEventListener('submit',event=>{event.preventDefault();const telegram=document.getElementById('telegram').value.trim(),amount=Number(document.getElementById('amount').value),product=document.getElementById('product').value,network=document.getElementById('network').value,txid=document.getElementById('txid').value.trim();const telegramOk=isValidTelegram(telegram),txidOk=isValidTransactionId(network,txid);setError('telegram',telegramOk?'':'Enter a valid username starting with @.');setError('amount',amount>=10?'':'Minimum deposit is 10 USDT.');setError('txid',txidOk?'':'Enter the completed payment TxID—not a wallet address.');if(!telegramOk||amount<10||!txidOk){showToast('Please correct the payment details');return}const message=['EVA AI MARKET — Payment Verification','',`Telegram username: ${telegram}`,`Product: ${product}`,`Amount: ${amount.toFixed(2)} USDT`,`Network: ${network}`,`Transaction ID: ${txid}`].join('\n');window.open(`https://t.me/eva007_8?text=${encodeURIComponent(message)}`,'_blank','noopener,noreferrer')});

function sortStoreProducts(products){return [...products].sort((a,b)=>{const aAws=a.category==='AWS Cloud Accounts',bAws=b.category==='AWS Cloud Accounts';if(aAws!==bAws)return aAws?-1:1;if(!aAws)return 0;const size=p=>{const text=`${p.name||''} ${p.subtitle||''}`;const match=text.match(/(\d{1,4})\s*(?:v?cpu|v\b)/i);return match?Number(match[1]):Number((p.name||'').match(/\d{1,4}/)?.[0]||0)};return size(b)-size(a)})}
const telegramQuoteServices=[
 {name:'Telegram Premium',subtitle:'3, 6 or 12-month official gift subscription'},
 {name:'Telegram Stars Recharge',subtitle:'Official Stars top-up for your Telegram account'},
 {name:'Telegram Ads Recharge',subtitle:'Telegram Ads balance top-up assistance'},
 {name:'Channel / Group Boost',subtitle:'Official boost setup for eligible channels and groups'},
 {name:'Telegram Giveaway',subtitle:'Premium or Stars giveaway setup assistance'},
 {name:'Telegram Recharge / Top-up',subtitle:'Custom official Telegram recharge service'}
];
function telegramQuoteCards(){return telegramQuoteServices.map(service=>`<article class="account-product panel telegram-service"><div class="product-logo claude-logo"><span>TG</span><i></i></div><span class="product-tag">Telegram Services</span><h3>${escapeStore(service.name)}</h3><p>${escapeStore(service.subtitle)}</p><strong>Custom <small>QUOTE</small></strong><div class="stock-line"><span class="in-stock">Available</span><span>Manual delivery</span></div><a class="button secondary" href="https://t.me/eva007_8?text=${encodeURIComponent('Hello, I want '+service.name+'. Please send the current price.')}" target="_blank" rel="noopener noreferrer">Contact for Price</a></article>`).join('')}

const publicStore=document.getElementById('public-store-products');
async function loadPublicStore(){if(!publicStore)return;try{const response=await fetch('/api/store');const body=await response.json();if(!response.ok)throw new Error(body.error||'Store unavailable');publicStore.innerHTML=sortStoreProducts(body.products).map(product=>`<article class="account-product panel">${publicProductLogo(product)}<span class="product-tag">${escapeStore(product.category)}</span><h3>${escapeStore(product.name)}</h3><p>${escapeStore(product.subtitle)}</p>${publicAwsFeatures(product)}<strong>$${Number(product.price_usd).toFixed(2)} <small>USDT</small></strong><div class="stock-line"><span class="${product.stock>0?'in-stock':'out-stock'}">${product.stock>0?product.stock+' in stock':'Out of stock'}</span><span>${product.warranty_days}-day warranty</span></div><a class="button ${product.stock>0?'secondary':'disabled'}" href="/login.html">${product.stock>0?'Buy with EVA Balance':'Unavailable'}</a></article>`).join('')+telegramQuoteCards()}catch(error){publicStore.innerHTML=`<article class="panel store-loading">${escapeStore(error.message)} Contact support for current stock.</article>`}}
function publicProductLogo(product){const aws=product.category==='AWS Cloud Accounts';return `<div class="product-logo ${aws?'aws-logo':'claude-logo'}"><span>${aws?'AWS':'AI'}</span><i></i></div>`}
function publicAwsFeatures(product){return product.category==='AWS Cloud Accounts'?'<ul class="aws-features"><li>Claude 4.6 / 4.7 / 4.8 Working</li><li>10K RPM</li><li>Full TDP</li><li>Invoice Paid · Old Account</li><li>Fable 5 Full Quota</li><li>Low Price · High Quality</li><li><a class="official-support-link" href="https://t.me/eva007_8" target="_blank" rel="noopener noreferrer">Contact Official Support</a></li></ul>':''}
function escapeStore(value){return String(value??'').replace(/[&<>'"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[c]))}
loadPublicStore();
