let client;
const money=value=>'$'+Number(value||0).toFixed(2);
const moneyPrecise=value=>'$'+Number(value||0).toFixed(6);
const escapeHtml=value=>String(value??'').replace(/[&<>'"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[c]));
const setNotice=(message,error=false)=>{const el=document.getElementById('dash-notice');el.textContent=message;el.className=error?'dash-notice error':'dash-notice success'};

async function getSession(){const {data:{session}}=await client.auth.getSession();if(!session){location.replace('/login.html');throw new Error('Sign in required.')}return session}
async function apiFetch(path,options={}){const session=await getSession();const response=await fetch(path,{...options,headers:{'content-type':'application/json',authorization:`Bearer ${session.access_token}`,...(options.headers||{})}});const body=await response.json().catch(()=>({}));if(!response.ok)throw new Error(body.error||'Request failed.');return body}
function renderRows(id,rows,mapper,colspan){const el=document.getElementById(id);if(el)el.innerHTML=rows.length?rows.map(mapper).join(''):`<tr><td colspan="${colspan}" class="empty">No records yet.</td></tr>`}

async function initDashboard(){try{const response=await fetch('/api/config');const config=await response.json();if(!response.ok)throw new Error(config.error||'Configuration unavailable');client=window.supabase.createClient(config.url,config.anonKey);const session=await getSession();document.getElementById('customer-email').textContent=session.user.email;await Promise.all([loadData(session.user.id),loadStore()])}catch(error){setNotice(error.message,true)}}

async function loadData(userId){const [wallet,deposits,ledger]=await Promise.all([client.from('wallets').select('balance_usd,updated_at').eq('user_id',userId).single(),client.from('deposits').select('id,amount_usdt,network,transaction_id,status,created_at').order('created_at',{ascending:false}).limit(20),client.from('wallet_ledger').select('amount_usd,entry_type,description,balance_after,created_at').order('created_at',{ascending:false}).limit(20)]);const firstError=[wallet,deposits,ledger].find(result=>result.error)?.error;if(firstError)throw firstError;document.getElementById('balance').textContent=moneyPrecise(wallet.data?.balance_usd);document.getElementById('pending-count').textContent=deposits.data.filter(item=>item.status==='pending').length;renderRows('deposit-rows',deposits.data,item=>`<tr><td>${new Date(item.created_at).toLocaleDateString()}</td><td>${escapeHtml(item.network)}</td><td>${money(item.amount_usdt)}</td><td><span class="status ${escapeHtml(item.status)}">${escapeHtml(item.status)}</span></td></tr>`,4);renderRows('ledger-rows',ledger.data,item=>`<tr><td>${new Date(item.created_at).toLocaleDateString()}</td><td>${escapeHtml(item.entry_type)}</td><td class="${Number(item.amount_usd)>=0?'positive':'negative'}">${moneyPrecise(item.amount_usd)}</td><td>${moneyPrecise(item.balance_after)}</td></tr>`,4)}

document.getElementById('dashboard-deposit-form').addEventListener('submit',async event=>{event.preventDefault();try{const {data:{user}}=await client.auth.getUser();if(!user)return location.replace('/login.html');const amount=Number(document.getElementById('dash-amount').value),network=document.getElementById('dash-network').value,transaction_id=document.getElementById('dash-txid').value.trim(),ownAddresses=new Set(['0x644ed89caecc120d3a3180e9f20a90d970cfa3e8','tj cfs6h dksenquguvw43krk141qlvhngbg'.replace(/ /g,'').toLowerCase()]),txValid=!ownAddresses.has(transaction_id.toLowerCase())&&((network==='BEP20'||network==='ERC20')?/^0x[a-fA-F0-9]{64}$/.test(transaction_id):/^[a-fA-F0-9]{64}$/.test(transaction_id));if(amount<10||!txValid)return setNotice('Enter at least 10 USDT and the completed payment TxID—not a wallet address.',true);const {error}=await client.from('deposits').insert({user_id:user.id,amount_usdt:amount,network,transaction_id});if(error)throw new Error(error.code==='23505'?'This transaction ID was already submitted.':error.message);setNotice('Deposit submitted. It is pending verification.');event.target.reset();await loadData(user.id)}catch(error){setNotice(error.message,true)}});

const telegramQuoteServices=[
 {name:'Telegram Premium',subtitle:'3, 6 or 12-month official gift subscription'},
 {name:'Telegram Stars Recharge',subtitle:'Official Stars top-up for your Telegram account'},
 {name:'Telegram Ads Recharge',subtitle:'Telegram Ads balance top-up assistance'},
 {name:'Channel / Group Boost',subtitle:'Official boost setup for eligible channels and groups'},
 {name:'Telegram Giveaway',subtitle:'Premium or Stars giveaway setup assistance'},
 {name:'Telegram Recharge / Top-up',subtitle:'Custom official Telegram recharge service'}
];
function dashboardTelegramCards(){return telegramQuoteServices.map(service=>`<article class="account-product panel telegram-service"><span class="product-tag">Telegram Services</span><h3>${escapeHtml(service.name)}</h3><p>${escapeHtml(service.subtitle)}</p><strong>Custom <small>QUOTE</small></strong><div class="stock-line"><span class="in-stock">Available</span><span>Manual delivery</span></div><a class="button secondary" href="https://t.me/eva007_8?text=${encodeURIComponent('Hello, I want '+service.name+'. Please send the current price.')}" target="_blank" rel="noopener noreferrer">Contact for Price</a></article>`).join('')}

async function loadStore(){try{const [catalog,orders]=await Promise.all([fetch('/api/store').then(async r=>{const b=await r.json();if(!r.ok)throw new Error(b.error||'Store unavailable');return b}),apiFetch('/api/store?view=orders')]);document.getElementById('dashboard-store-products').innerHTML=catalog.products.map(product=>`<article class="account-product panel"><span class="product-tag">${escapeHtml(product.category)}</span><h3>${escapeHtml(product.name)}</h3><p>${escapeHtml(product.subtitle)}</p><strong>${money(product.price_usd)} <small>USDT</small></strong><div class="stock-line"><span class="${product.stock>0?'in-stock':'out-stock'}">${product.stock>0?product.stock+' in stock':'Out of stock'}</span><span>${product.warranty_days}-day warranty</span></div><button class="button ${product.stock>0?'primary':'disabled'} buy-product" data-product-id="${escapeHtml(product.id)}" data-product-name="${escapeHtml(product.name)}" data-product-price="${Number(product.price_usd)}" ${product.stock>0?'':'disabled'}>${product.stock>0?'Buy now':'Unavailable'}</button></article>`).join('')+dashboardTelegramCards();document.querySelectorAll('.buy-product').forEach(button=>button.addEventListener('click',()=>buyProduct(button)));renderRows('order-rows',orders.orders,item=>`<tr><td>${new Date(item.created_at).toLocaleDateString()}</td><td>${escapeHtml(item.product_name)}</td><td>${money(item.price_usd)}</td><td><span class="status ${escapeHtml(item.status)}">${escapeHtml(item.status)}</span></td><td>${item.delivery_details?`<pre>${escapeHtml(item.delivery_details)}</pre>`:'Pending admin delivery'}</td></tr>`,5)}catch(error){setNotice(error.message,true)}}

async function buyProduct(button){const name=button.dataset.productName||'this product',price=Number(button.dataset.productPrice||0);if(!confirm(`Buy ${name} for ${price.toFixed(2)}? Your EVA balance will be deducted immediately.`))return;button.disabled=true;try{await apiFetch('/api/store',{method:'POST',body:JSON.stringify({productId:button.dataset.productId})});setNotice('Purchase successful. Balance deducted and order set to Processing. The admin will deliver it securely.');const {data:{user}}=await client.auth.getUser();if(user)await Promise.all([loadData(user.id),loadStore()])}catch(error){setNotice(error.message,true);button.disabled=false}}

document.getElementById('sign-out').addEventListener('click',async()=>{await client.auth.signOut();location.replace('/')});
initDashboard();
